services:
  - type: web
    name: ai-chatbot-saas-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://your-frontend-domain.com
      - key: WIDGET_CDN_URL
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: SEED_DATABASE
        value: true

  - type: pserv
    name: ai-chatbot-saas-postgres
    env: docker
    plan: free
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1